In [105]:
import pandas as pd
import numpy as np

In [106]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")
df.head(10)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
5,2007,USA,Hybrid,Front-wheel drive,2,2290,6,266.0,4260,18.8,31.2
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
7,2005,USA,Gasoline,Front-wheel drive,4,2370,6,279.0,4090,17.4,30.2
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
9,2004,USA,Diesel,All-wheel drive,5,2330,6,280.0,4620,17.7,31.2

In [107]:
df = df[['engine_displacement','horsepower','vehicle_weight','model_year','fuel_efficiency_mpg']]
df.head(5)

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
0,2180,243.0,3870,2006,31.9
1,2390,272.0,4210,2008,31.3
2,2320,267.0,4240,1996,27.5
3,2130,258.0,4490,1989,28.5
4,2580,304.0,4510,1994,31.0

In [108]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  10000 non-null  int64
 1   horsepower           9123 non-null   float64
 2   vehicle_weight       10000 non-null  int64
 3   model_year           10000 non-null  int64
 4   fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 390.8 KB

In [109]:
df['horsepower'].median()

np.float64(254.0)

In [110]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

np.random.seed(42)
idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]
df_test = df.iloc[idx[n_train + n_val:]]

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [111]:
df_train['horsepower'] = df_train['horsepower'].fillna(0)
df_val['horsepower'] = df_val['horsepower'].fillna(0)

In [112]:
X_train = df_train[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
X_val = df_val[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values

In [113]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)

    w = XTX_inv.dot(X.T).dot(y)

    return w[0], w[1:]

In [114]:
def rmse(y, y_pred):
    error = y_pred - y
    mse = (error ** 2).mean()
    return np.sqrt(mse)

In [115]:
w_0, w = train_linear_regression(X_train, y_train)
y_pred = w_0 + X_val.dot(w)

In [116]:
round(rmse(y_val, y_pred), 3)

np.float64(2.854)

In [117]:
df_train['horsepower'] = df_train['horsepower'].fillna(df_train['horsepower'].mean())
df_val['horsepower'] = df_val['horsepower'].fillna(df_train['horsepower'].mean())

In [118]:
X_train = df_train[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
X_val = df_val[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values

In [119]:
w0, w = train_linear_regression(X_train, y_train)

y_pred = w0 + X_val.dot(w)

round(rmse(y_val, y_pred), 3)

np.float64(2.854)

In [78]:
w_0, w = train_linear_regression_reg(X_train, y_train, 100)

y_pred = w_0 + X_val.dot(w)

round(rmse(y_val, y_pred), 4)

np.float64(0.0735)

In [90]:
y = df['fuel_efficiency_mpg'].values

seeds = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
scores = []

In [91]:
for seed in seeds:
    idx = np.arange(len(df))
    np.random.seed(seed)
    np.random.shuffle(idx)

    n_train = int(0.6 * len(df))
    n_val = int(0.2 * len(df))

    train_idx = idx[:n_train]
    val_idx = idx[n_train:n_train + n_val]

    df_train = df.iloc[train_idx].copy()
    df_val = df.iloc[val_idx].copy()

    df_train['horsepower'] = df_train['horsepower'].fillna(0)
    df_val['horsepower'] = df_val['horsepower'].fillna(0)

    X_train = df_train[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
    X_val = df_val[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values

    y_train = df_train['fuel_efficiency_mpg'].values
    y_val = df_val['fuel_efficiency_mpg'].values

    w0, w = train_linear_regression(X_train, y_train)

    y_pred = w0 + X_val.dot(w)

    score = rmse(y_val, y_pred)
    scores.append(score)

scores

[np.float64(2.239204143046126),
 np.float64(2.2021128210838845),
 np.float64(2.1634197787530947),
 np.float64(2.2043588768539224),
 np.float64(2.2018800943311554),
 np.float64(2.2457851509085134),
 np.float64(2.2697212079524043),
 np.float64(2.190794599933443),
 np.float64(2.216611201686444),
 np.float64(2.2070365928178957)]

In [92]:
np.std(scores)

np.float64(0.028781274078191175)

In [93]:
np.random.seed(9)

n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]].copy()
df_val = df.iloc[idx[n_train:n_train + n_val]].copy()
df_test = df.iloc[idx[n_train + n_val:]].copy()

print(len(df_train), len(df_val), len(df_test))

6000 2000 2000

In [94]:
df_full_train = pd.concat([df_train, df_val])

df_full_train['horsepower'] = df_full_train['horsepower'].fillna(0)
df_test['horsepower'] = df_test['horsepower'].fillna(0)

In [95]:
X_full_train = df_full_train[
    ['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']
].values

y_full_train = df_full_train['fuel_efficiency_mpg'].values

X_test = df_test[
    ['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']
].values

y_test = df_test['fuel_efficiency_mpg'].values

In [71]:
def train_linear_regression_reg(X, y, r):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])

    XTX = X.T.dot(X)
    XTX = XTX + r * np.eye(XTX.shape[0])

    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv.dot(X.T).dot(y)

    return w[0], w[1:]

In [79]:
y = np.log1p(df['fuel_efficiency_mpg'].values)

In [80]:
seeds = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
scores = []

In [81]:
np.random.seed(0)
idx = np.arange(len(df))
np.random.shuffle(idx)

n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

df_train = df.iloc[idx[:n_train]].reset_index(drop=True)
df_val = df.iloc[idx[n_train:n_train + n_val]].reset_index(drop=True)
df_test = df.iloc[idx[n_train + n_val:]].reset_index(drop=True)

y_train = y[idx[:n_train]]
y_val = y[idx[n_train:n_train + n_val]]

In [84]:
scores = []

for seed in seeds:
    np.random.seed(seed)
    idx = np.arange(len(df))
    np.random.shuffle(idx)

    df_train = df.iloc[idx[:n_train]].reset_index(drop=True)
    df_val = df.iloc[idx[n_train:n_train + n_val]].reset_index(drop=True)

    y_train = y[idx[:n_train]]
    y_val = y[idx[n_train:n_train + n_val]]

    df_train['horsepower'] = df_train['horsepower'].fillna(0)
    df_val['horsepower'] = df_val['horsepower'].fillna(0)

    X_train = df_train[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
    X_val = df_val[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values

    w_0, w = train_linear_regression(X_train, y_train)

    y_pred = w_0 + X_val.dot(w)

    scores.append(rmse(y_val, y_pred))

In [85]:
scores

[np.float64(0.07222016116435427),
 np.float64(0.07085480962390553),
 np.float64(0.07001674410142289),
 np.float64(0.07160947080490032),
 np.float64(0.07121934602793346),
 np.float64(0.07272074319560708),
 np.float64(0.07363981939829586),
 np.float64(0.07093670406151323),
 np.float64(0.07159357901409524),
 np.float64(0.07162894692635216)]

In [88]:
np.std(scores)

np.float64(0.0009710806116187275)

In [96]:
w0, w = train_linear_regression_reg(X_full_train, y_full_train, r=0.001)

y_pred = w0 + X_test.dot(w)

rmse(y_test, y_pred)

np.float64(2.235827747191731)