In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")
df.head(10)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
5,2007,USA,Hybrid,Front-wheel drive,2,2290,6,266.0,4260,18.8,31.2
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
7,2005,USA,Gasoline,Front-wheel drive,4,2370,6,279.0,4090,17.4,30.2
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
9,2004,USA,Diesel,All-wheel drive,5,2330,6,280.0,4620,17.7,31.2

In [3]:
df = df[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year', 'fuel_efficiency_mpg']]
df.head(5)

,engine_displacement,horsepower,vehicle_weight,model_year,fuel_efficiency_mpg
0,2180,243.0,3870,2006,31.9
1,2390,272.0,4210,2008,31.3
2,2320,267.0,4240,1996,27.5
3,2130,258.0,4490,1989,28.5
4,2580,304.0,4510,1994,31.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  10000 non-null  int64
 1   horsepower           9123 non-null   float64
 2   vehicle_weight       10000 non-null  int64
 3   model_year           10000 non-null  int64
 4   fuel_efficiency_mpg  10000 non-null  float64
dtypes: float64(2), int64(3)
memory usage: 390.8 KB

In [5]:
df['horsepower'].median()

np.float64(254.0)

In [6]:
n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

np.random.seed(42)
idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]
df_test = df.iloc[idx[n_train + n_val:]]

In [7]:
df_train['horsepower'] = df_train['horsepower'].fillna(0)
df_val['horsepower'] = df_val['horsepower'].fillna(0)

X_train = df_train[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
X_val = df_val[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values

y_train = df_train['fuel_efficiency_mpg'].values
y_val = df_val['fuel_efficiency_mpg'].values

In [8]:
def train_linear_regression(X, y):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])
    XTX = X.T.dot(X)
    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv.dot(X.T).dot(y)
    return w[0], w[1:]

In [9]:
def rmse(y, y_pred):
    error = y_pred - y
    mse = (error ** 2).mean()
    return np.sqrt(mse)

In [10]:
w0, w = train_linear_regression(X_train, y_train)
y_pred = w0 + X_val.dot(w)
round(rmse(y_val, y_pred), 3)

np.float64(2.205)

In [11]:
np.random.seed(42)
idx = np.arange(len(df))
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]

df_train['horsepower'] = df_train['horsepower'].fillna(df_train['horsepower'].mean())
df_val['horsepower'] = df_val['horsepower'].fillna(df_train['horsepower'].mean())

X_train = df_train[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
X_val = df_val[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values

y_train = df_train['fuel_efficiency_mpg'].values
y_val = df_val['fuel_efficiency_mpg'].values

In [12]:
w0, w = train_linear_regression(X_train, y_train)
y_pred = w0 + X_val.dot(w)
round(rmse(y_val, y_pred), 3)

np.float64(2.202)

In [13]:
def train_linear_regression_reg(X, y, r):
    ones = np.ones(X.shape[0])
    X = np.column_stack([ones, X])
    XTX = X.T.dot(X)
    XTX = XTX + r * np.eye(XTX.shape[0])
    XTX_inv = np.linalg.inv(XTX)
    w = XTX_inv.dot(X.T).dot(y)
    return w[0], w[1:]

In [14]:
np.random.seed(42)
idx = np.arange(len(df))
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:n_train + n_val]]

df_train['horsepower'] = df_train['horsepower'].fillna(0)
df_val['horsepower'] = df_val['horsepower'].fillna(0)

X_train = df_train[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
X_val = df_val[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values

y_train = df_train['fuel_efficiency_mpg'].values
y_val = df_val['fuel_efficiency_mpg'].values

In [15]:
for r in [0, 0.01, 0.1, 1, 5, 10, 100]:
    w0, w = train_linear_regression_reg(X_train, y_train, r)
    y_pred = w0 + X_val.dot(w)
    print(r, round(rmse(y_val, y_pred), 4))

0 2.2053
0.01 2.2058
0.1 2.2241
1 2.3492
5 2.4094
10 2.4195
100 2.4292

In [16]:
seeds = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
scores = []

for seed in seeds:
    idx = np.arange(len(df))
    np.random.seed(seed)
    np.random.shuffle(idx)

    n_train = int(0.6 * len(df))
    n_val = int(0.2 * len(df))

    train_idx = idx[:n_train]
    val_idx = idx[n_train:n_train + n_val]

    df_train = df.iloc[train_idx].copy()
    df_val = df.iloc[val_idx].copy()

    df_train['horsepower'] = df_train['horsepower'].fillna(0)
    df_val['horsepower'] = df_val['horsepower'].fillna(0)

    X_train = df_train[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
    X_val = df_val[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values

    y_train = df_train['fuel_efficiency_mpg'].values
    y_val = df_val['fuel_efficiency_mpg'].values

    w0, w = train_linear_regression(X_train, y_train)
    y_pred = w0 + X_val.dot(w)

    scores.append(rmse(y_val, y_pred))

np.std(scores)

np.float64(0.028781274078191175)

In [17]:
np.random.seed(9)

n = len(df)
n_val = int(n * 0.2)
n_test = int(n * 0.2)
n_train = n - n_val - n_test

idx = np.arange(n)
np.random.shuffle(idx)

df_train = df.iloc[idx[:n_train]].copy()
df_val = df.iloc[idx[n_train:n_train + n_val]].copy()
df_test = df.iloc[idx[n_train + n_val:]].copy()

df_full_train = pd.concat([df_train, df_val])

df_full_train['horsepower'] = df_full_train['horsepower'].fillna(0)
df_test['horsepower'] = df_test['horsepower'].fillna(0)

X_full_train = df_full_train[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
y_full_train = df_full_train['fuel_efficiency_mpg'].values

X_test = df_test[['engine_displacement', 'horsepower', 'vehicle_weight', 'model_year']].values
y_test = df_test['fuel_efficiency_mpg'].values

In [18]:
w0, w = train_linear_regression_reg(X_full_train, y_full_train, r=0.001)
y_pred = w0 + X_test.dot(w)
rmse(y_test, y_pred)

np.float64(2.235827747191731)